import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {randomBytes,scryptSync} from 'node:crypto';
import os from 'node:os';import path from 'node:path';
import {createTelegramService} from './telegram-bot.mjs';

const SECRET='very-long-checkout-test-webhook-secret';
let temp,proc,base,cookie,orderId,orderToken,claimCode,bot,updates=2000;
const request=(url,method='GET',body,headers={})=>fetch(base+url,{method,headers:{...headers,...(body&&!Buffer.isBuffer(body)?{'Content-Type':'application/json'}:{})},body:body?(Buffer.isBuffer(body)?body:JSON.stringify(body)):undefined});
const auth=(url,method='GET',body)=>request(url,method,body,{Cookie:cookie});
const msg=(text,from=42)=>({update_id:updates++,message:{chat:{id:from,type:'private'},from:{id:from},text}});
const cb=(data,from=42)=>({update_id:updates++,callback_query:{id:'q'+updates,from:{id:from},data,message:{chat:{id:from}}}});
before(async()=>{
 temp=await mkdtemp(path.join(os.tmpdir(),'taklifly-card-'));
 const port=31000+Math.floor(Math.random()*10000);base='http://127.0.0.1:'+port;
 const password='test-strong-admin-123',salt=randomBytes(16).toString('hex');
 proc=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port),DATA_DIR:temp,NODE_ENV:'test',ADMIN_USERNAME:'admin',ADMIN_PASSWORD_HASH:salt+':'+scryptSync(password,salt,64).toString('hex'),ADMIN_SESSION_SECRET:randomBytes(50).toString('hex'),TELEGRAM_BOT_TOKEN:'',TELEGRAM_WEBHOOK_SECRET:''},stdio:'ignore'});
 let running=false;
 for(let i=0;i<90;i++){try{if((await fetch(base+'/health')).ok){running=true;break}}catch{}await new Promise(r=>setTimeout(r,80))}
 assert.equal(running,true);
 const response=await request('/api/admin/login','POST',{username:'admin',password});
 assert.equal(response.status,200);
 cookie=response.headers.get('set-cookie').split(';')[0];
 bot=createTelegramService({dataDir:temp,baseUrl:base,botToken:'TEST_TOKEN',webhookSecret:SECRET,transport:async(method,params)=>{record.push({method,params});return true}});
});
after(async()=>{proc?.kill();await rm(temp,{recursive:true,force:true})});
const record=[];
test('independent card checkout disabled until details configured',async()=>{
 const r=await request('/api/checkout/catalog');assert.equal(r.status,200);
 const list=(await r.json()).templates;assert.equal(list.length,3);
 const details=await (await request('/api/checkout/payment-details')).json();assert.equal(details.configured,false);assert.equal(details.cardNumber,null);
 const order=await request('/api/checkout/orders','POST',{template:'oq-saroy',customerName:'Alisher',contact:'@testuser'});
 assert.equal(order.status,503);
 assert.equal((await request('/api/admin/card/settings')).status,401);
 assert.equal((await request('/api/admin/card/orders')).status,401);
});
test('admin card receiver and prices enable standalone payment order',async()=>{
 let r=await auth('/api/admin/card/settings','PUT',{cardNumber:'8600 1111 2222 3333',cardHolder:'TOHIRBEK TESTOV',prices:{'oq-saroy':250000,zarhal:300000,minimal:150000}});
 assert.equal(r.status,200);
 r=await request('/api/checkout/payment-details');const d=await r.json();assert.equal(d.configured,true);assert.equal(d.cardHolder,'TOHIRBEK TESTOV');
 assert.equal(d.cardNumber,'8600111122223333');
 r=await request('/api/checkout/orders','POST',{template:'zarhal',customerName:'Ali Valiyev',contact:'@alivali'});
 assert.equal(r.status,201);
 const o=await r.json();orderId=o.orderId;orderToken=o.accessToken;
 assert.equal(o.amount,300000);assert.equal(o.status,'awaiting_receipt');
 assert.equal((await request('/api/checkout/orders/'+orderId)).status,404);
 r=await request('/api/checkout/orders/'+orderId,'GET',null,{'X-Order-Token':orderToken});assert.equal(r.status,200);
 const detail=await r.json();assert.equal(detail.claimCode,null);assert.equal(detail.customerName,'Ali Valiyev');
 assert.equal((await auth('/api/admin/card/receipts/'+orderId)).status,404);
});
test('receipt is private, requires verification, then issues activation code',async()=>{
 const bytes=Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),randomBytes(480)]);
 let r=await request('/api/checkout/orders/'+orderId+'/receipt','POST',bytes,{'X-Order-Token':orderToken,'Content-Type':'image/png'});
 assert.equal(r.status,200);
 assert.equal((await r.json()).status,'review');
 assert.equal((await request('/api/admin/card/receipts/'+orderId)).status,401);
 r=await auth('/api/admin/card/receipts/'+orderId);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/png');
 assert.equal(Buffer.from(await r.arrayBuffer()).length,bytes.length);
 const blocked=await request('/api/checkout/orders/'+orderId,'GET',null,{'X-Order-Token':orderToken});
 assert.equal((await blocked.json()).claimCode,null);
 r=await auth('/api/admin/card/orders/'+orderId,'PATCH',{status:'approved'});assert.equal(r.status,200);
 r=await request('/api/checkout/orders/'+orderId,'GET',null,{'X-Order-Token':orderToken});
 const st=await r.json();assert.equal(st.status,'approved');assert.match(st.claimCode,/^TKF-[A-F0-9]{24}$/);claimCode=st.claimCode;
 assert.equal((await auth('/api/admin/card/orders/'+orderId,'PATCH',{status:'approved'})).status,409);
});
test('approved website code activates once and bot sends named guest invitation post',async()=>{
 await bot.processUpdate(msg('/redeem '+claimCode));
 assert.ok(record.some(x=>x.method==='sendMessage'&&x.params.text.includes('qabul qilindi')));
 await bot.processUpdate(msg('/redeem '+claimCode,81));
 assert.ok(record.findLast(x=>x.method==='sendMessage').params.text.includes('boshqa akkauntga'));
 const orders=await bot.getOrders();const o=orders.find(x=>x.cardOrderId===orderId);
 assert.ok(o);assert.equal(o.status,'collecting');assert.equal(o.template,'zarhal');
 const steps=['Azizbek','Maftuna','18.09.2027','18:00','Baxor restorani','Toshkent, Shayxontohur 15'];
 for(const val of steps)await bot.processUpdate(msg(val));
 await bot.processUpdate(cb('skip:'+o.id));
 await bot.processUpdate(cb('skip:'+o.id));
 await bot.processUpdate(cb('skip:'+o.id));
 await bot.processUpdate(cb('skip:'+o.id));
 const ready=await bot.getOrders();assert.equal(ready.find(x=>x.id===o.id).step,'review');
 await bot.processUpdate(cb('publish:'+o.id));
 let pub=await request('/i/'+o.slug);assert.equal(pub.status,200);
 const html=await pub.text();assert.ok(html.includes('Azizbek'));assert.ok(html.includes('Maftuna'));
 await bot.processUpdate(cb('order:'+o.id));
 assert.ok(record.findLast(x=>x.method==='sendMessage').params.reply_markup.inline_keyboard.flat().some(x=>x.callback_data==='invite:'+o.id));
 await bot.processUpdate(cb('invite:'+o.id));
 await bot.processUpdate(msg('Sardor aka'));
 const last=record.findLast(x=>x.method==='sendMessage').params;
 assert.ok(last.text.includes('Hurmatli Sardor aka'));
 assert.ok(last.text.includes('/i/'+o.slug+'?guest=Sardor%20aka'));
 assert.ok(last.reply_markup.inline_keyboard.flat().some(b=>String(b.url||'').includes('t.me/share/url')));
 const updated=await bot.getOrders();assert.equal(updated.find(x=>x.id===o.id).guestLinks[0].name,'Sardor aka');
});
